### PR TITLE
recipes-kernel: Load multimedia related modules automatically

### PR DESCRIPTION
**Pull request by rshym**
Which is equivalent to the following command:
modprobe -a mmngr mmngrbuf vspm_if uvcs_drv

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>

### CODE REVIEW

**Comment by rshym** [comment]
This is clone of following patch from meta-xt-prod-devel:
```
commit d4286f7beb64fc16ee0f684d390a68bfe4d8b3dc
Author: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
Date:   Thu Dec 5 16:13:28 2019 +0200

    domd: recipes-kernel: Load multimedia related modules automatically
    
    Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
```

**Comment by rshym** [comment]
@otyshchenko1 @lorc @iusyk 
Could you please review?

**Review by iusyk — APPROVED** [review]
Reviewed-by: Ihor Usyk <ihor_usyk@epam.com>

**Comment by rshym** [comment]
Reviewer is added.

**Pull request merged**
