### PR TITLE
[New ATF recipe] atf: Rework recipe

### PR DESCRIPTION
**Pull request by rshym**

### CODE REVIEW

**Comment by rshym** [comment]
This PR is expected to work together with https://github.com/xen-troops/meta-xt-rcar/pull/15

**Comment by rshym** [comment]
@lorc Could you please look into this PR?
I feel that It's not "well done", and need some more "roasting".
Also, https://github.com/xen-troops/meta-xt-rcar/pull/15 is an additional part of this change.

**Comment by rshym** [comment]
@otyshchenko1 @lorc 
Could you please take a look into this PR, when possible?
I will be glad to hear all your comments because I understand that this PR is far from the best possible solution.

**Comment by lorc** [comment]
Hi @rshym,

You did a good job reworking this recipe. I'm fine with the code itself, but there are some comments:

1. This is patch for `meta-renesas`. We generally don't want to make own changes to `meta-renesas`. We have this layer on XenTroops Github only because Renesas provides some patches on top of their own layer. As we don't want Moulin to patch downloaded code, we store patches version on our GitHub. 

So, in my opinion you need to move this recipe to `meta-xt-rcar/meta-xt-rcar-fixups`. Also, it would be cool to create PR to Renesas GitHub. Dunno if they will take it, but we can try at lest.

2. You need to split this patch into two parts:  first one should rework build and second one should add our own patches.

**Comment by rshym** [comment]
Thanks!
I will rework PR.

**Pull request closed without merging**
